#!/usr/bin/env python3
"""
Regenerates podcast.html from live sources (re-runnable):
  - YouTube playlist RSS  -> newest episode (hero) + the next 9 (cards), with video embeds
  - iTunes lookup API     -> per-episode Apple Podcasts links (matched by title)
  Spotify links point to the show (per-episode needs their API).

RUN:  python3 build-podcast.py     (then commit + push)

No external libraries (standard library only). Update the IDs below if the show moves.
"""
import urllib.request, json, re, html as htmlmod, datetime, os, difflib

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "podcast.html")
ASSET_V = "7"

YT_PLAYLIST = "PLQihvuykg8UaJqy5CnF2Fok8MDdoNuZ66"
ITUNES_ID = "1554806227"
APPLE_SHOW = "https://podcasts.apple.com/us/podcast/peter-lohmanns-podcast/id1554806227"
SPOTIFY_SHOW = "https://open.spotify.com/show/5BLsN2TwI8mDtIhGoKfnZV?si=be32f2f710c84d67"
YT_CHANNEL = "https://www.youtube.com/@peterlohmann/podcasts"
YT_PLAYLIST_URL = f"https://www.youtube.com/playlist?list={YT_PLAYLIST}"
UA = {"User-Agent": "Mozilla/5.0"}

def get(url):
    return urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=40).read().decode("utf-8", "replace")

def clean_title(t):
    t = htmlmod.unescape(t or "").strip()
    t = re.split(r"\s*\|\s*Peter Lohmann", t)[0]      # drop "| Peter Lohmann's Podcast"
    t = re.split(r"\s*\|\s*", t)[0]                    # drop any trailing "| ..."
    return t.strip()

def fetch_youtube():
    xml = get(f"https://www.youtube.com/feeds/videos.xml?playlist_id={YT_PLAYLIST}")
    entries = re.findall(r"<entry>(.*?)</entry>", xml, re.S)
    eps = []
    for e in entries:
        vid = (re.search(r"<yt:videoId>([^<]+)</yt:videoId>", e) or [None, None])
        vid = re.search(r"<yt:videoId>([^<]+)</yt:videoId>", e)
        title = re.search(r"<media:title>([^<]+)</media:title>", e) or re.search(r"<title>([^<]+)</title>", e)
        pub = re.search(r"<published>([^<]+)</published>", e)
        if not vid:
            continue
        eps.append({"id": vid.group(1), "title": clean_title(title.group(1) if title else ""),
                    "date": pub.group(1)[:10] if pub else ""})
    return eps

def fetch_apple():
    try:
        d = json.loads(get(f"https://itunes.apple.com/lookup?id={ITUNES_ID}&country=US&media=podcast&entity=podcastEpisode&limit=30"))
    except Exception:
        return []
    out = []
    for r in d.get("results", []):
        if r.get("wrapperType") == "podcastEpisode" and r.get("trackViewUrl"):
            out.append({"title": r.get("trackName") or "", "url": r.get("trackViewUrl")})
    return out

def norm(s):
    return re.sub(r"[^a-z0-9]+", " ", (s or "").lower()).strip()

def match_apple(yt_title, apple):
    nt = norm(yt_title)
    best, score = None, 0.0
    for a in apple:
        s = difflib.SequenceMatcher(None, nt, norm(a["title"])).ratio()
        if s > score:
            best, score = a, s
    return best["url"] if best and score >= 0.55 else None

def fmt_date(d):
    try:
        return datetime.datetime.strptime(d, "%Y-%m-%d").strftime("%b ") + str(int(d[8:10])) + ", " + d[:4]
    except Exception:
        return ""

def esc(s):
    return htmlmod.escape(s or "", quote=True)

def card(ep, apple_url):
    apple = apple_url or APPLE_SHOW
    date = fmt_date(ep["date"])
    return f"""        <div class="ep-card">
          <div class="ep-player" data-id="{ep['id']}" role="button" tabindex="0" aria-label="Play: {esc(ep['title'])}">
            <img src="https://i.ytimg.com/vi/{ep['id']}/hqdefault.jpg" alt="" loading="lazy" />
            <span class="ep-play" aria-hidden="true"></span>
          </div>
          <div class="ep-body">
            {'<div class="ep-date">'+esc(date)+'</div>' if date else ''}
            <h3>{esc(ep['title'])}</h3>
            <div class="ep-links">
              <a class="ep-btn apple" href="{esc(apple)}" target="_blank" rel="noopener">Apple</a>
              <a class="ep-btn spotify" href="{esc(SPOTIFY_SHOW)}" target="_blank" rel="noopener">Spotify</a>
            </div>
          </div>
        </div>"""

def build():
    yt = fetch_youtube()
    apple = fetch_apple()
    if not yt:
        raise SystemExit("No YouTube episodes found; aborting (leaving podcast.html unchanged).")
    hero = yt[0]
    cards = yt[1:10]
    print(f"Hero: {hero['title']} ({hero['id']})")
    cards_html = "\n".join(card(ep, match_apple(ep["title"], apple)) for ep in cards)
    matched = sum(1 for ep in cards if match_apple(ep["title"], apple))
    print(f"Cards: {len(cards)}  (Apple per-episode matches: {matched}/{len(cards)})")

    page = f"""<!-- GENERATED by build-podcast.py (YouTube playlist RSS + iTunes API). Re-run to refresh episodes. -->
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Podcast &middot; Peter Lohmann</title>
<meta name="description" content="Peter Lohmann's Podcast: honest, operator-to-operator conversations about property management. Watch the latest episodes, or listen on Apple Podcasts and Spotify." />
<link rel="icon" type="image/svg+xml" href="favicon.svg" />
<link rel="icon" type="image/png" sizes="32x32" href="favicon-32.png" />
<link rel="apple-touch-icon" href="favicon.png" />
<link rel="stylesheet" href="styles.css?v={ASSET_V}" />
</head>
<body>
<a class="skip" href="#main">Skip to content</a>
<nav class="top" aria-label="Primary">
  <div class="bar">
    <a class="brand" href="index.html">Peter <span>Lohmann</span></a>
    <button class="nav-toggle" aria-expanded="false" aria-controls="navlinks">Menu</button>
    <div class="links" id="navlinks">
      <a href="index.html">About</a>
      <a href="newsletter.html">Newsletter</a>
      <a href="podcast.html" class="active">Podcast</a>
      <a href="largest-pm-companies.html">Largest PM Companies</a>
      <a href="blog.html">Blog</a>
      <a href="report/index.html" target="_blank" rel="noopener">M&amp;A Report</a>
      <a href="peterbot.html">PeterBot</a>
      <a href="products.html">Products</a>
    </div>
    <a class="btn btn-navy btn-sm cta" href="contact.html">Contact</a>
  </div>
</nav>
<main id="main">
  <header class="page-hero">
    <div class="wrap">
      <div class="ticks" aria-hidden="true"><i></i><i></i><i></i></div>
      <span class="kicker">🎙️ The Podcast</span>
      <h1>Honest, operator-to-operator conversations.</h1>
      <p class="lead">100+ episodes across six seasons. Interviews with fellow business owners and executives about growth, hiring, systems, and the realities of leadership. No fluff, just smart people talking shop.</p>
    </div>
  </header>

  <!-- LATEST EPISODE (newest video) -->
  <section class="band">
    <div class="wrap">
      <div class="split" style="align-items:center;">
        <div>
          <span class="tag tag-warn">Latest episode</span>
          <h2 class="h-lead" style="margin:14px 0 10px;">{esc(hero['title'])}</h2>
          <p class="sub">Fresh conversations drop regularly. Hit play, or catch the full back catalog on the platform of your choice.</p>
          <div class="listen-row mt-sm">
            <a class="btn btn-primary" href="{YT_PLAYLIST_URL}" target="_blank" rel="noopener">▶ Full episode playlist</a>
          </div>
        </div>
        <div>
          <div class="embed-frame video">
            <iframe src="https://www.youtube.com/embed/{hero['id']}" title="{esc(hero['title'])}"
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                    referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- RECENT EPISODES (cards) -->
  <section class="band tight">
    <div class="wrap">
      <span class="kicker">Recent Episodes</span>
      <h2 class="h-lead">More to watch and hear.</h2>
      <p class="sub" style="margin-bottom:22px;">Tap any episode to play it right here, or listen on your platform of choice.</p>
      <div class="ep-grid">
{cards_html}
      </div>
      <div class="center mt-lg">
        <a class="btn btn-ghost" href="{YT_CHANNEL}" target="_blank" rel="noopener">See all episodes on YouTube</a>
      </div>
    </div>
  </section>

  <!-- STATS -->
  <section class="band tight wash" aria-label="At a glance">
    <div class="wrap">
      <div class="stats stats-color">
        <div class="stat"><div class="v">100+</div><div class="k">Episodes published</div></div>
        <div class="stat"><div class="v">6</div><div class="k">Seasons and counting</div></div>
        <div class="stat"><div class="v">20k+</div><div class="k">Weekly audience across the platform</div></div>
      </div>
    </div>
  </section>

  <!-- LISTEN ANYWHERE -->
  <section class="band">
    <div class="wrap center">
      <span class="kicker">Listen &amp; Subscribe</span>
      <h2 class="h-lead">Catch it wherever you listen.</h2>
      <p class="sub" style="margin:8px auto 0;">Tune in, turn up the property know-how, and have a blast while you're at it.</p>
      <div class="listen-row mt-md" style="justify-content:center;">
        <a class="listen-btn" href="{APPLE_SHOW}" target="_blank" rel="noopener">🎧 Apple Podcasts</a>
        <a class="listen-btn" href="{SPOTIFY_SHOW}" target="_blank" rel="noopener">🟢 Spotify</a>
        <a class="listen-btn" href="{YT_CHANNEL}" target="_blank" rel="noopener">▶️ YouTube</a>
      </div>
    </div>
  </section>

  <!-- SPONSOR -->
  <section class="band tight">
    <div class="wrap">
      <div class="panel orange">
        <span class="tag tag-warn">Want to sponsor?</span>
        <h2 class="h-lead" style="margin-top:14px;">Reach the audience.</h2>
        <p class="sub">Get targeted exposure to over 20,000 property management professionals every week across the newsletter and podcast.</p>
        <a class="btn btn-primary mt-sm" href="contact.html">Explore sponsorship</a>
      </div>
    </div>
  </section>
</main>
<footer class="site">
  <div class="wrap">
    <div class="foot-grid">
      <div class="brand" style="font-weight:700;color:var(--navy);">Peter <span style="color:var(--primary);">Lohmann</span></div>
      <nav class="foot-links" aria-label="Footer">
        <a href="index.html">About</a>
        <a href="newsletter.html">Newsletter</a>
        <a href="podcast.html">Podcast</a>
        <a href="largest-pm-companies.html">Largest PM Companies</a>
        <a href="blog.html">Blog</a>
        <a href="report/index.html" target="_blank" rel="noopener">M&amp;A Report</a>
        <a href="peterbot.html">PeterBot</a>
        <a href="products.html">Products</a>
        <a href="featured.html">Featured</a>
        <a href="contact.html">Contact</a>
        <a href="https://www.linkedin.com/in/pslohmann/" target="_blank" rel="noopener">LinkedIn</a>
      </nav>
    </div>
    <p class="disc">The content of this website is for informational purposes only and does not constitute professional advice. I may have consulting agreements with, or financial interests in, companies mentioned on this website. Additionally, some of the links across this site may be affiliate links, meaning I may earn a commission if you make a purchase through those links. Always perform your own due diligence before making any financial or business decisions.</p>
  </div>
</footer>
<script src="site.js?v={ASSET_V}"></script>
</body>
</html>
"""
    with open(OUT, "w") as f:
        f.write(page)
    print(f"Wrote {OUT}")

if __name__ == "__main__":
    build()
